### ISSUE TITLE
Npm Package Empty

### ISSUE THREAD

**Issue by evans** [bcherny/flow-to-typescript#2]
Downloading the 1.0.0 package brought in a tar with only a package.json. A normally install `npm install -D flow-to-typscript` does not bring in any of the code.

```
╰─ [INSERT]  ➤  npm view flow-to-typescript dist.tarball
https://registry.npmjs.org/flow-to-typescript/-/flow-to-typescript-1.0.0.tgz
```

Maybe another publish will solve the issue

**Comment by bcherny** [comment]
Hi @evans! This package isn't ready to go unfortunately. I published to NPM to reserve the name while I work on this package. If you'd like to help, please see #1 :)
